// <auto-generated />
using System;
using ContainerAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContainerAPI.Migrations
{
    [DbContext(typeof(ContextoDaAPI))]
    [Migration("20221212192219_Container")]
    partial class Container
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContainerAPI.Models.Container", b =>
                {
                    b.Property<int>("containerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("containerId"), 1L, 1);

                    b.Property<string>("clienteNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("containerCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("containerNumero")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("containerStatusVazio")
                        .HasColumnType("bit");

                    b.Property<string>("containerTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("containerId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("ContainerAPI.Models.Movimentacao", b =>
                {
                    b.Property<int>("movimentacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("movimentacaoId"), 1L, 1);

                    b.Property<int>("containerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("movimentacaoFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("movimentacaoInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("movimentacaoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("movimentacaoId");

                    b.HasIndex("containerId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("ContainerAPI.Models.Movimentacao", b =>
                {
                    b.HasOne("ContainerAPI.Models.Container", "Container")
                        .WithMany("Movimentacao")
                        .HasForeignKey("containerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("ContainerAPI.Models.Container", b =>
                {
                    b.Navigation("Movimentacao");
                });
#pragma warning restore 612, 618
        }
    }
}
